### ISSUE TITLE
Encountering error running flo at early 'faSplit' step: 

### ISSUE THREAD

**Issue by rtraborn** [wurmlab/flo#17]
Hi:
I ran flo to liftOver from one nematode genome assembly to another (Pristionchus pacificus)
`Command failed with status (127): [faSplit sequence run/target.fa 2 run/chunk...]`

Here's the full command:
```
>$ rake -f Rakefile
mkdir run
cp /scratch/rtraborn/pp_liftOver/pp_hybrid1/Pristionchus_Hybrid_assembly.fa run/source.fa
cp /scratch/rtraborn/pp_liftOver/pp_hybrid2/pacificus_Hybrid2.fa run/target.fa
faToTwoBit run/source.fa run/source.2bit
/usr/local/share/gems/gems/rake-12.3.0/lib/rake/file_utils.rb:54: warning: Insecure world writable dir /home/rtraborn/genome_analysis/paml4.9d/bin in PATH, mode 040777
faToTwoBit run/target.fa run/target.2bit
twoBitInfo run/source.2bit stdout | sort -k2nr > run/source.sizes
twoBitInfo run/target.2bit stdout | sort -k2nr > run/target.sizes
faSplit sequence run/target.fa 2 run/chunk_
rake aborted!
Command failed with status (127): [faSplit sequence run/target.fa 2 run/chunk...]
/home/rtraborn/genome_analysis/flo/Rakefile:79:in `block in <top (required)>'
/home/rtraborn/genome_analysis/flo/Rakefile:37:in `block in <top (required)>'
/usr/local/share/gems/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => run/liftover.chn
(See full trace by running task with --trace)
```

Concerning the opts file: I set `blat_opts:` as follows: `'-tileSize=12 -minIdentity=98'` and set `processes:` to '2'.

Any idea where this is going wrong? I'm certain the assemblies and gff file are correctly formatted (the latter being 'cleaned' as described.

**Comment by yeban** [comment]
Hey. Thanks for being patient. This looks like `faSplit` command could not be found, or is not executable. Otherwise, running the command `faSplit sequence run/target.fa 2 run/chunk_` directly in the command line can help understand what's going on.

**Comment by rtraborn** [comment]
Hi @yeban. Thanks so much- I'll give that a shot and let you know how that goes.

**Comment by rtraborn** [comment]
@yeban for the record this worked well. Sorry I neglected to follow up. Cheers!
