### ISSUE TITLE
Results and discussion

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/flo#20]
Hi,
How did you calculate the below percentage? 
> For an ant genome (~350 Mb) we saw 90% annotations map identically to the new assembly (unpublished result).

Is it possible to get more statistics out of Flo?

Thank you in advance.

Michal

**Comment by yannickwurm** [comment]
Wait who are you working with?

**Comment by mictadlo** [comment]
I am working with plants and I was just wondering how I could calculate similar statistics from flo results.

**Comment by mictadlo** [comment]
Did I choose the right data to calculate how much annotations map identically to the new assembly?
```
ls
input.cds.fa  input.gff  lifted_cleaned.cds.fa  lifted_cleaned.gff  lifted.gff3  unlifted.gff3  unmapped.txt

> grep "ID=" unlifted.gff3 | wc -l
19233
> grep "ID=" lifted_cleaned.gff | wc -l
33639
> wc -l unmapped.txt 
43632 unmapped.txt
> grep "ID=" input.gff | wc -l
45857
> python 
>>> float(33639*100)/45857
73.35630329066446
```
Thank you in advance,

Michal
