### ISSUE TITLE
faToTwoBit: cannot execute binary file

### ISSUE THREAD

**Issue by divyanandu** [wurmlab/flo#23]
I am trying to lift over a viral genome from one version to another. I am getting the following error when doing that. I checked the permissions of the faToTwoBit file and that looks fine. I am running this on a Mac

Error:
mkdir run
cp /Users/divya/NC_009333.fa run/source.fa
cp /Users/divya/GQ994935.fa run/target.fa
faToTwoBit run/source.fa run/source.2bit
ext/kent/bin/faToTwoBit: ext/kent/bin/faToTwoBit: cannot execute binary file
rake aborted!
Command failed with status (126): [faToTwoBit run/source.fa run/source.2bit...]
/Users/divya/flo/Rakefile:127:in `to_2bit'
/Users/divya/flo/Rakefile:72:in `block in <top (required)>'
/Users/divya/flo/Rakefile:37:in `block in <top (required)>'
Tasks: TOP => run/liftover.chn

**Comment by yeban** [comment]
Is it possible that you downloaded Linux version of the executables on the Mac? This can be the case if you used the `install.sh` script, which is meant to be for Linux (I realize that's not clear in the README - sorry).

**Comment by divyanandu** [comment]
Thats exactly what I did. I will try and install the mac version and see if that solved the problem. Thanks!

**Comment by divyanandu** [comment]
Is there a list of dependencies that I need to install?

**Comment by yeban** [comment]
Tools listed in [`install.sh`](https://github.com/wurmlab/flo/blob/master/scripts/install.sh) script.

**Comment by yeban** [comment]
I updated install.sh to download for linux or mac depending on you computer.
