### ISSUE TITLE
flo compilation error

### ISSUE THREAD

**Issue by El-Castor** [wurmlab/flo#30]
Hi, 

I've try to install flo but when I launch the install using install.sh I've a compilation error in return : 

`genometools-1.5.6/www/genometools.org/htdocs/trackselectors.html
genometools-1.5.6/www/github/
genometools-1.5.6/www/github/assets/
genometools-1.5.6/www/github/assets/overview.png
/bin/sh: 1: Syntax error: "(" unexpected
/bin/sh: 1: Syntax error: "(" unexpected
/bin/sh: 1: Syntax error: "(" unexpected
[compile sqlite3.o]
/bin/sh: 2: Syntax error: "(" unexpected
make: *** [Makefile:741: obj/src/external/sqlite-3.8.7.1/sqlite3.o] Error 2`

I've you got any idea to fix this issue ?

Thanks in advance

**Comment by yeban** [comment]
Sorry, no idea
