### ISSUE TITLE
Workflow manager?

### ISSUE THREAD

**Issue by photocyte** [wurmlab/flo#31]
Any plans to wrap flo in a workflow manager, e.g. snakemake or nextflow?  This could help it run on many different platforms.

The reason I ask is, I discovered flo after writing my own nextflow pipeline to do something similar, but it doesn't fully work, so I might try to wrap flo in a workflow manager instead. If you are already working on doing that maybe we can join forces?
https://github.com/photocyte/doSameSpeciesLiftOver_nextflow

**Comment by yeban** [comment]
I don't plan to wrap flo in a workflow manager. I am happy for you to do so, either as part of this repository or elsewhere. My plans for flo are documented in #27.

If I understood 'Known issues #1' of your repo correctly, I think splitting sequences into 5 kb chunks is problematic for chain file creation only if the chunks end up in different files. To work around that, in flo, I ensure that all 5kb chunks of a big scaffold always stays in the same file (L92 and 95 of Rakefile).
