### ISSUE TITLE
Syntax issue with rake

### ISSUE THREAD

**Issue by 14zac2** [wurmlab/flo#35]
Hello!

I'm having trouble getting flo started. I was hoping you might be able to help me out. To set up flo, I installed all dependencies using apt-get or conda (`conda create -n flo -c mvdbeek -c conda-forge parallel genometools ucsc_tools`). I set up my data as requested, and am now getting the following error:

`rake aborted!`
`SyntaxError: /path/to/dir/opts_example.yaml:16: syntax error, unexpected ':', expecting end-of-input`

Often I encounter errors because my directory has spaces in it (can't change this), but I don't think this is the problem, here. In my opts file, the line throwing the error is as such:

`:source_fa: '/path/to/genome/genome.fa'`

Do you have any idea what might be going on here? Some sort of version error, perhaps?

Thanks,
Zoe

**Comment by yeban** [comment]
It looks like you are running flo something like `rake -f /path/to/dir/opts_example.yaml` when it should be `rake -f /path/to/flo/Rakefile`.
- `Rakefile` is the pipeline script that comes with flo.
- flo will automatically look for config file, specifically called `flo_opts.yaml` in the directory you run the above command in.

**Comment by 14zac2** [comment]
Perfect, that was my misunderstanding! Thanks for clarifying, it works now! :)
