### ISSUE TITLE
Expecting number line ERROR

### ISSUE THREAD

**Issue by matoller** [wurmlab/flo#40]
Hello, I want to thank you for create this amazing tool and helping people with their flo issues.
I am having a problem with a flo run and I am not able to solve it. I think is related with the gff file but I dont know what is the problem (I downloaded it directly from NCBI).
These are the files I am using to run flo [flo_files.zip](https://github.com/wurmlab/flo/files/7941611/flo_files.zip)
- "new" is the source
- "old" is the target

Here is the error: 

> liftOver -gff /home/jose/flo_haloferax/new.gff run/liftover.chn run/new/lifted.gff3 run/new/unlifted.gff3
Reading liftover chains
Mapping coordinates
WARNING: -gff is not recommended.
Use 'ldHgGene -out=<file.gp>' and then 'liftOver -genePred <file.gp>'
Expecting number line 12 of /home/jose/flo_haloferax/new.gff
rake aborted!
Command failed with status (255): [liftOver -gff /home/jose/flo_haloferax/new...]
/home/jose/flo/Rakefile:45:in `block (2 levels) in <top (required)>'
/home/jose/flo/Rakefile:40:in `each'
/home/jose/flo/Rakefile:40:in `block in <top (required)>'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => default

I tryed to preprocess the gff file using `gt gff3 -tidy -sort -addids -retainids` and also to delete the gene feature with `gff_remove_feats.rb gene` but the same error appears.

Thank you so much in advance!

**Comment by matoller** [comment]
Problem solved. The .gff file has some features that seem to be not campatible with flo. I removed them to simplify the file and it finally worked.

**Comment by yannickwurm** [comment]
Thanks for the update @matoller  - apologies for our lack of response. Typically the main issues are with gffs having too much info / or weird fields in them.  

Take care
