### ISSUE TITLE
cc command not found

### ISSUE THREAD

**Issue by RNAseqer** [wurmlab/flo#41]
Hi there, I'm attempting to run flo on a cluster and I kept getting an error: 

<img width="827" alt="image" src="https://user-images.githubusercontent.com/100554377/157274850-86faff7e-b8d9-4962-ac7c-ddff456c58f0.png">

For users on HPC clusters, I would suggest changing the install.sh to include make CC=gcc cairo=no errorcheck=no for genometools.  

This ended up working for me.

**Comment by yeban** [comment]
Thank you for letting us know.
