### ISSUE TITLE
install.sh fails with a make error for libgenometoools.so

### ISSUE THREAD

**Issue by Npaffen** [wurmlab/flo#43]
One should update the makefile so that the newest version of [genometools](https://github.com/genometools/genometools) is used in the building process. Right now version 1.5.6 can lead to the following make error :

```
flo_species_name/ext/genometools-1.5.6/src/mgth/metagenomethreader.h:224: multiple definition of `gt_cstr_nofree_ulp_hashtype'; obj/src/mgth/metagenomethreader.o:/media/nils/nils_ssd_01/flo_species_name/ext/genometools-1.5.6/src/mgth/metagenomethreader.h:224: first defined here
/usr/bin/ld: obj/src/mgth/mg_compute_gene_prediction.o
collect2: error: ld returned 1 exit status
make: *** [Makefile:587: lib/libgenometools.so] Error 1
```
To prevent this just adjust the make file section referring to the installation of genometools like this : 

```
# Genometools
cd ext
wget -c https://github.com/genometools/genometools/archive/refs/tags/v1.6.2.tar.gz -O v1.6.2.tar.gz
tar xvf v1.6.2.tar.gz
rm v1.6.2.tar.gz
cd genometools-1.6.2
make cairo=no errorcheck=no

```

**Comment by yannickwurm** [comment]
Thank you for debugging this [Npaffen](https://github.com/Npaffen)!

Might you be able to submit a pull request with this change?

**Comment by Npaffen** [comment]
Done! Maybe a short question out of curiosity: How long should the creation of a chain file for two different human genome assemblies take with 23 threads on a Ryzen 9 5900X and 128GB RAM. I don't expect an exact answer but just a rough estimate. 1 minute, 30 minutes, an hour, 3 hours?
