### ISSUE TITLE
Rakefile error when attempting to run flo

### ISSUE THREAD

**Issue by sessmurda** [wurmlab/flo#5]
Hi,

I was able to fix the previous error I posted about, but reached another in the final steps of processing on a sample run. I am unsure which database is missing, but I did receive the lifted/unlifted gff files which look reasonable so far. Any help finishing the last steps of the analysis would be greatly appreciated, log file copied below:

cat error.log 
nohup: ignoring input
/global/u2/a/asession/SCRIPTS/flo/Rakefile:25: warning: Insecure world writable dir /global/common/genepool/usg/languages/R in PATH, mode 040777
mkdir run
cp ./Chr1L.example/Chr1L.v91.fa run/source.fa
cp ./Chr1L.example/Chr1L.v92.fa run/target.fa
faToTwoBit run/source.fa run/source.2bit
faToTwoBit run/target.fa run/target.2bit
twoBitInfo run/source.2bit stdout | sort -k2nr > run/source.sizes
twoBitInfo run/target.2bit stdout | sort -k2nr > run/target.sizes
faSplit sequence run/target.fa 1 run/chunk_
parallel --joblog run/joblog.faSplit -j 1 -a run/joblst.faSplit
43201 pieces of 43961 written
parallel --joblog run/joblog.blat -j 1 -a run/joblst.blat
Loaded 219879705 letters in 1 sequences
Searched 216002468 bases in 43201 sequences
parallel --joblog run/joblog.liftUp -j 1 -a run/joblst.liftUp
Got 43201 lifts in run/chunk_0.fa.lft
Lifting run/chunk_0.fa.psl
parallel --joblog run/joblog.axtChain -j 1 -a run/joblst.axtChain
693297 blocks after duplicate removal
Loaded 219802468 bases of NC_030724.1 from run/target.2bit
Loaded 219879705 bases of chr1L from run/source.2bit
chainPair NC_030724.1-chr1L
Main chaining step done in 2979 milliseconds
747068 blocks after duplicate removal
chainPair NC_030724.1+chr1L
Main chaining step done in 14412 milliseconds
parallel --joblog run/joblog.chainSort -j 1 -a run/joblst.chainSort
chainMergeSort run/*.chn.sorted | chainSplit run stdin -lump=1
mv run/000.chain run/combined.chn.sorted
chainNet run/combined.chn.sorted run/source.sizes run/target.sizes run/combined.chn.sorted.net /dev/null
Got 1 chroms in run/source.sizes, 1 in run/target.sizes
Finishing nets
writing run/combined.chn.sorted.net
writing /dev/null
netChainSubset run/combined.chn.sorted.net run/combined.chn.sorted run/liftover.chn
Processing chr1L
mkdir Chr1L-liftover-Chr1L.v92
liftOver -gff ./Chr1L.example/Chr1L.gff3 run/liftover.chn Chr1L-liftover-Chr1L.v92/lifted.gff3 Chr1L-liftover-Chr1L.v92/unlifted.gff3
Reading liftover chains
Mapping coordinates
WARNING: -gff is not recommended.
Use 'ldHgGene -out=<file.gp>' and then 'liftOver -genePred <file.gp>'
rake aborted!
LoadError: cannot load such file -- bio/db/gff

**Comment by yeban** [comment]
Sorry for slow response. Running `gem install bio` (or `sudo gem install bio`) should resolve that.
