### ISSUE TITLE
Rakefile issue

### ISSUE THREAD

**Issue by kbrevs** [wurmlab/flo#6]
Hey, this seems similar to another recent issue (involving the bio gem not being installed), but I am running into this issue now, and I am unsure what the error is indicating - if it is an issue with my gff or with ruby. Here is the trace, followed by the first three lines of my .gff.

rake --trace                                                                                                                                                                  [ 3:01PM]
** Invoke default (first_time)
** Execute default
** Invoke run/liftover.chn (first_time, not_needed)
mkdir lepdec_OGSv1.0_ONLY_GENES.gff-liftover-Ldec_redundans_on_alpaths_contigs_genome
liftOver -gff lepdec_OGSv1.0_ONLY_GENES.gff run/liftover.chn lepdec_OGSv1.0_ONLY_GENES.gff-liftover-Ldec_redundans_on_alpaths_contigs_genome/lifted.gff3 lepdec_OGSv1.0_ONLY_GENES.gff-liftover-Ldec_redundans_on_alpaths_contigs_genome/unlifted.gff3
Reading liftover chains
Mapping coordinates
WARNING: -gff is not recommended.
Use 'ldHgGene -out=<file.gp>' and then 'liftOver -genePred <file.gp>'
/var/lib/gems/2.2.0/gems/bio-1.5.1/lib/bio/db/gff.rb:921: warning: regexp match /.../n against to UTF-8 string
rake aborted!
undefined method `last' for nil:NilClass
/home/beetle/Documents/CPB/reference_genomes/flo/Rakefile:72:in `block in process_gff'
/home/beetle/Documents/CPB/reference_genomes/flo/Rakefile:69:in `each'
/home/beetle/Documents/CPB/reference_genomes/flo/Rakefile:69:in `group_by'
/home/beetle/Documents/CPB/reference_genomes/flo/Rakefile:69:in `process_gff'
/home/beetle/Documents/CPB/reference_genomes/flo/Rakefile:223:in `block (2 levels) in <top (required)>'
/home/beetle/Documents/CPB/reference_genomes/flo/Rakefile:212:in `each'
/home/beetle/Documents/CPB/reference_genomes/flo/Rakefile:212:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:170:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:143:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:95:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:73:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:70:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => default

GFF: 
Scaffold1       OGSv1.0 gene    12481   16948   .       -       .       ID=LDEC000001;Name=LDEC000001;Dbxref=I5KNAL:LDEC000001;method=Maker
Scaffold1       OGSv1.0 gene    19920   23242   .       -       .       ID=LDEC000002;Name=LDEC000002;Dbxref=I5KNAL:LDEC000002;method=Maker
Scaffold1       OGSv1.0 gene    26074   37602   .       +       .       ID=LDEC000003;Name=LDEC000003;Dbxref=I5KNAL:LDEC000003;method=Maker

Thanks!
Kristian

**Comment by yeban** [comment]
Hey. I made some changes to flo to address this. Do you think you can test it?

**Comment by kbrevs** [comment]
Great, thank you! I just ran it, and got new error messages:
rake --trace                                                                                                                                                                  [ 9:34AM]
** Invoke default (first_time)
** Execute default
** Invoke run/liftover.chn (first_time)
** Execute run/liftover.chn
mkdir run
cp Ldec.genome.10062013.fa run/source.fa
cp Ldec_redundans_on_alpaths_contigs_genome.fa run/target.fa
faToTwoBit run/source.fa run/source.2bit
faToTwoBit run/target.fa run/target.2bit
twoBitInfo run/source.2bit stdout | sort -k2nr > run/source.sizes
twoBitInfo run/target.2bit stdout | sort -k2nr > run/target.sizes
faSplit sequence run/target.fa 20 run/chunk_
rake aborted!
Command failed with status (127): [faSplit sequence run/target.fa 20 run/chun...]
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:53:in `block in create_shell_runner'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:45:in `call'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:45:in `sh'
/usr/lib/ruby/vendor_ruby/rake/file_utils_ext.rb:37:in `sh'
/home/beetle/Documents/CPB/reference_genomes/flov2/flo/Rakefile:175:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:170:in `invoke'
/home/beetle/Documents/CPB/reference_genomes/flov2/flo/Rakefile:222:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `call'
/usr/lib/ruby/vendor_ruby/rake/task.rb:246:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:241:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:184:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:177:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:170:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:143:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:101:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:95:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:73:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:70:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => run/liftover.chn


I failed to add that I was able to run it successfully on a different gff (which I later realized was an outdated annotation set. It looks like the formatted isn't preserved by github, but here are the first few lines of the gff which did run to completion (I wasn't able to discern a formatting difference): 

Scaffold1   WebApollo   gene    1790498 1794021 .   +   .   Name=916B82F966EEA6552CB9A3AFD9F1B307;date_creation=2014-07-21;owner=spalli;ID=916B82F966EEA6552CB9A3AFD9F1B307;date_last_modified=2014-09-24
Scaffold1   WebApollo   mRNA    1790498 1794021 .   +   .   Name=conserved oligomeric golgi complex subunit 1 ;date_creation=2014-07-21;Parent=916B82F966EEA6552CB9A3AFD9F1B307;symbol=IdICP;description=ExScaffold1   WebApollo   exon    1790660 1790887 .   +   .   Name=0C0A7D3097A5D5F597D2E77A89F9FAB5;date_creation=2014-07-21;Parent=62272803AB84FD406888F0C4BC209A78;owner=spalli;ID=0C0A7D3097A5D5F597D2E77A

Thanks!

**Comment by yeban** [comment]
I think this new error is unrelated and is caused by somehow flo not being able to find `faSplit` command.

**Comment by kbrevs** [comment]
Yes, you are correct - a migration issue. Teach me to do things so early on a Monday. :) Looks like it is running perfect now. Thanks!
