### ISSUE TITLE
Not processing gff

### ISSUE THREAD

**Issue by pgonzale60** [wurmlab/flo#8]
Hi!

The lift over chaining works like a charm, however it crashes when trying to process_gff. The issue seems to come from line 62 in the rakefile: require 'bio/db/gff'
I don't know if I need to install something in order to make this work.

Error shows:
`liftOver -gff dwil_flybase.gff3 run/liftover.chn dwil_flybase-liftover-dwil_JR/lifted.gff3 dwil_flybase-liftover-dwil_JR/unlifted.gff3
Reading liftover chains
Mapping coordinates
WARNING: -gff is not recommended.
Use 'ldHgGene -out=<file.gp>' and then 'liftOver -genePred <file.gp>'
rake aborted!
LoadError: cannot load such file -- bio/db/gff
/home/pgonzale/Programs/flo/Rakefile:62:in `process_gff'
/home/pgonzale/Programs/flo/Rakefile:234:in `block (2 levels) in <top (required)>'
/home/pgonzale/Programs/flo/Rakefile:223:in `each'
/home/pgonzale/Programs/flo/Rakefile:223:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)
`

Greetings!

**Comment by yeban** [comment]
Hey. If you could just run `gem install bio` and rerun flo, that should do it.

(run `sudo gem install bio` if `gem install bio` doesn't work)

**Comment by yeban** [comment]
closing note - added BioRuby to dependencies section in README
