### ISSUE TITLE
expecting number line 38 of gff3

### ISSUE THREAD

**Issue by olechnwin** [wurmlab/flo#9]
Hi,

I am trying to liftover the ref_GRCh37.p13_top_level.gff3 to a denovo-assembled genome. but got the following error:
mkdir ref_GRCh37.p13_top_level-liftover-A673_combined_fastq.1
liftOver -gff /gpfs0/home/rslssnck/cxt050/hg19/ref_GRCh37.p13_top_level.gff3 run/liftover.chn ref_GRCh37.p13_top_level-liftover-A673_combined_fastq.1/lifted.gff3 ref_GRCh37.p13_top_level-liftover-A673_combined_fastq.1/unlifted.gff3
Reading liftover chains
Mapping coordinates
WARNING: -gff is not recommended.
Use 'ldHgGene -out=<file.gp>' and then 'liftOver -genePred <file.gp>'
Expecting number line 38 of /gpfs0/home/rslssnck/cxt050/hg19/ref_GRCh37.p13_top_level.gff3
rake aborted!
Command failed with status (255): [liftOver -gff /gpfs0/home/rslssnck/cxt0...]
/gpfs0/home/rslssnck/cxt050/opt/flo/Rakefile:232:in `block (2 levels) in <top (required)>'
/gpfs0/home/rslssnck/cxt050/opt/flo/Rakefile:223:in `each'
/gpfs0/home/rslssnck/cxt050/opt/flo/Rakefile:223:in `block in <top (required)>'
/gpfs0/home/rslssnck/cxt050/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)

I'm not sure what to do with this error. Your help is greatly appreciated. Thanks!

**Comment by yeban** [comment]
Looks like the input gff file is not valid. You can use genometools to check gff files (`gt gff3 -sort -tidy -retainids  ref_GRCh37.p13_top_level.gff3`).
